### PR TITLE
Upgrade slate version to 2.7.1

### PR DESCRIPTION
**Pull request by chenyixuan625**
Upgrade slate to 2.7.1 to fix the broken TOC.

Verification:
The regular tutorial could regenerate and its table of contents shows up.

Screenshot of the GitHub page:
Screen Shot 2020-11-04 at 12 10 11 PM

### CODE REVIEW

**Comment by shriniketsarkar** [comment]
Was there no way of updating the slate version in a separate PR and then using the new version to fix the issue in 2 separate PR's ?

**Comment by chenyixuan625** [comment]
> Was there no way of updating the slate version in a separate PR and then using the new version to fix the issue in 2 separate PR's ?

The issue is actually caused by the slate version too old so this PR is for updating the slate to the latest version. After using the latest version, we won't have the TOC issue anymore. The reason I committed a new [commit](https://github.com/cerner/smart-on-fhir-tutorial/pull/139/commits/155948cc700f512e007dd3552ec86bd7cfeec6f2) (155948c) is I changed some dependencies during cherry-picking the previous commit. So I have to revert it back to match the latest slate version requires. And also our Cerner code logo picture got lost during the update so add it back as well.

**Review by beichhor — CHANGES_REQUESTED** [review]
There seems to be quite a few files that I would necessarily expect from this PR. Such as the issue templates, pr templates, github action files, dockerignore file, etc.

**Comment by chenyixuan625** [comment]
> There seems to be quite a few files that I would necessarily expect from this PR. Such as the issue templates, pr templates, github action files, dockerignore file, etc.

These files are imported by [commit](https://github.com/cerner/smart-on-fhir-tutorial/pull/139/commits/852b2325a849c82d34dffbf4b53fd0409a280df1) which is the rebase commit with the cerner/slate_update branch. A new commit is pushed to get rid of these unnecessary files. Thank you for reminding me!

**Comment by shriniketsarkar** [comment]
My initial thought about how this update can be done was : 
- in a new branch we will pull in the slate latest version say we call this branch slate_latest
- we create another branch from ```slate_latest``` say named as ```slate_latest_tutorial_update```
- on ```slate_latest_tutorial_update``` we squash merge changes from ```main``` or ```gh-pages``` branch 
- we issue a PR off ```slate_latest_tutorial_update``` to land on ```slate_latest```.
- once this PR is done our branch ```slate_latest``` will have all the code for a working tutorial.
- we replace the ```main``` and ```gh-pages``` branch with this new branch to publish the tutorial. 

This will make it clean such that we now will have all updates to the latest slate and on top of it a single commit of our tutorial code. 
@beichhor 
@jfrhong  
thoughts on this approach?

**Pull request closed without merging**
